theme: jekyll-theme-cayman
home_title: "乔布立斯Blog"
paginate: 5 
paginate_path: "/archive/page:num/"
plugins:
  - jekyll-paginate
  - jekyll-json
  - jekyll-archives
excerpt_separator: <!--more-->
include:
  - search.json
baseurl: ""

jekyll-archives:
  enabled:
    - tags
  layouts:
    tag: 'tagpage'   # 自定义布局名称
  permalinks:
    tag: '/tags/:name/'
markdown: kramdown
highlighter: rouge   # 或 pygments