name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - master  # 当 `main` 分支有更新时触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: 设置 Ruby 环境
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # 选择 Jekyll 支持的 Ruby 版本
      # 缓存依赖
      - name: Cache Bundler dependencies
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      # Step 3: 安装 Jekyll 和 Bundler
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      # Step 4: 构建静态网站
      - name: Build the site
        run: bundle exec jekyll build

      # Step 5: 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  